# Eating Data Preprocessing

This notebook loads, combines, and processes all participant CSVs in the `dataprocessing` folder for eating event analysis.

# Import Libraries

In [95]:
import pandas as pd
import glob
import re
import numpy as np

# Load and Combine CSV Files

In [96]:
# Load all CSVs from the 'dataprocessing' folder and add Participant_ID from the filename
csv_files = glob.glob('dataprocessing/*.csv')

# Sort files numerically by participant ID (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, ...)
csv_files.sort(key=lambda x: int(x.split('/')[-1].split('.')[0]))

csv_data_frames = []
pattern = re.compile(r'^dataprocessing/(\d+)(?:-(\d+))?\.csv')

for csv_file in csv_files:
    match = pattern.match(csv_file)
    if match:
        participant_id = int(match.group(1))  # Extract participant ID from filename
        df = pd.read_csv(csv_file)
        df = df.drop('Volume', axis=1)  # Delete Volume column
        df['Participant_ID'] = participant_id
        csv_data_frames.append(df)
        print(f"Loaded: {csv_file} -> Participant_ID: {participant_id}")
    else:
        print(f'Skipping file with invalid naming format: {csv_file}')

if csv_data_frames:
    combined_csv_data = pd.concat(csv_data_frames, ignore_index=True)
    print('\nCombined Data:')
    print(f"Total rows: {len(combined_csv_data)}")
    print(f"Participant IDs in order: {sorted(combined_csv_data['Participant_ID'].unique())}")
    display(combined_csv_data.head(10))  # Show first 10 rows for inspection
else:
    print('No valid CSV data found. Make sure the CSV files are in the correct format.')

Loaded: dataprocessing/1.csv -> Participant_ID: 1
Loaded: dataprocessing/2.csv -> Participant_ID: 2
Loaded: dataprocessing/3.csv -> Participant_ID: 3
Loaded: dataprocessing/4.csv -> Participant_ID: 4
Loaded: dataprocessing/5.csv -> Participant_ID: 5
Loaded: dataprocessing/6.csv -> Participant_ID: 6
Loaded: dataprocessing/7.csv -> Participant_ID: 7
Loaded: dataprocessing/8.csv -> Participant_ID: 8
Loaded: dataprocessing/9.csv -> Participant_ID: 9
Loaded: dataprocessing/10.csv -> Participant_ID: 10
Loaded: dataprocessing/11.csv -> Participant_ID: 11
Loaded: dataprocessing/12.csv -> Participant_ID: 12
Loaded: dataprocessing/13.csv -> Participant_ID: 13
Loaded: dataprocessing/14.csv -> Participant_ID: 14
Loaded: dataprocessing/15.csv -> Participant_ID: 15
Loaded: dataprocessing/16.csv -> Participant_ID: 16
Loaded: dataprocessing/17.csv -> Participant_ID: 17
Loaded: dataprocessing/18.csv -> Participant_ID: 18
Loaded: dataprocessing/19.csv -> Participant_ID: 19
Loaded: dataprocessing/20.csv -> Participant_ID: 20
Loaded: dataprocessing/21.csv -> Participant_ID: 21
Loaded: dataprocessing/22.csv -> Participant_ID: 22
Loaded: dataprocessing/23.csv -> Participant_ID: 23
Loaded: dataprocessing/24.csv -> Participant_ID: 24
Loaded: dataprocessing/25.csv -> Participant_ID: 25
Loaded: dataprocessing/26.csv -> Participant_ID: 26

Combined Data:
Total rows: 25872
Participant IDs in order: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26)]

,Time,Zone_0,Zone_1,Zone_2,Zone_3,Zone_4,Zone_5,Zone_6,Zone_7,Zone_8,...,Zone_56,Zone_57,Zone_58,Zone_59,Zone_60,Zone_61,Zone_62,Zone_63,Label,Participant_ID
0,1752232693000,2024,2078,263,332,2109,2166,63,2139,2011,...,236,198,190,188,199,208,244,1916,Not_Drinking,1
1,1752232693200,2010,2028,226,332,2199,199,162,2136,2013,...,199,187,185,183,198,209,256,1887,Not_Drinking,1
2,1752232693400,2024,2078,242,332,2163,254,76,2136,2011,...,213,187,185,183,198,209,248,1916,Not_Drinking,1
3,1752232694000,2037,2070,242,332,2163,199,76,2132,2013,...,213,186,179,178,187,209,248,1973,Not_Drinking,1
4,1752232694200,2037,2079,309,265,258,232,76,2116,2017,...,216,186,179,178,187,204,229,1988,Not_Drinking,1
5,1752232694400,2039,2145,309,232,246,232,85,1957,2017,...,218,189,182,181,188,204,229,1973,Not_Drinking,1
6,1752232694600,2039,2146,309,232,256,232,85,1950,2017,...,218,195,183,181,188,205,241,195,Not_Drinking,1
7,1752232694800,2061,2151,2160,280,246,197,85,1903,2021,...,217,195,182,181,187,205,241,193,Not_Drinking,1
8,1752232695000,2061,2174,2178,288,256,197,2261,1903,2021,...,217,193,180,180,187,205,249,163,Not_Drinking,1
9,1752232695200,2038,2174,2178,288,231,208,2261,1920,2015,...,223,189,179,179,184,203,238,163,Not_Drinking,1

# Change 'Drinking' to 'Eating'

In [97]:
# Replace all occurrences of the label 'Drinking' with 'Eating', but keep 'Not_Drinking' as is
if 'Label' in combined_csv_data.columns:
    combined_csv_data['Label'] = combined_csv_data['Label'].replace('Drinking', 'Eating')
    print(combined_csv_data['Label'].value_counts())
    display(combined_csv_data.head(10))  # Show first 10 rows for inspection
else:
    print('No Label column found in the data.')

Label
Not_Drinking    24262
Eating           1610
Name: count, dtype: int64

,Time,Zone_0,Zone_1,Zone_2,Zone_3,Zone_4,Zone_5,Zone_6,Zone_7,Zone_8,...,Zone_56,Zone_57,Zone_58,Zone_59,Zone_60,Zone_61,Zone_62,Zone_63,Label,Participant_ID
0,1752232693000,2024,2078,263,332,2109,2166,63,2139,2011,...,236,198,190,188,199,208,244,1916,Not_Drinking,1
1,1752232693200,2010,2028,226,332,2199,199,162,2136,2013,...,199,187,185,183,198,209,256,1887,Not_Drinking,1
2,1752232693400,2024,2078,242,332,2163,254,76,2136,2011,...,213,187,185,183,198,209,248,1916,Not_Drinking,1
3,1752232694000,2037,2070,242,332,2163,199,76,2132,2013,...,213,186,179,178,187,209,248,1973,Not_Drinking,1
4,1752232694200,2037,2079,309,265,258,232,76,2116,2017,...,216,186,179,178,187,204,229,1988,Not_Drinking,1
5,1752232694400,2039,2145,309,232,246,232,85,1957,2017,...,218,189,182,181,188,204,229,1973,Not_Drinking,1
6,1752232694600,2039,2146,309,232,256,232,85,1950,2017,...,218,195,183,181,188,205,241,195,Not_Drinking,1
7,1752232694800,2061,2151,2160,280,246,197,85,1903,2021,...,217,195,182,181,187,205,241,193,Not_Drinking,1
8,1752232695000,2061,2174,2178,288,256,197,2261,1903,2021,...,217,193,180,180,187,205,249,163,Not_Drinking,1
9,1752232695200,2038,2174,2178,288,231,208,2261,1920,2015,...,223,189,179,179,184,203,238,163,Not_Drinking,1

In [98]:
# ====================================================================
# Assign sip_id in batches: each batch = Not_Drinking + Eating, sequentially
# ====================================================================

def add_sip_id_batch(df):
    """
    For each participant, assign sip_id in batches:
    - Each batch consists of a Not_Drinking segment followed by an Eating segment.
    - Both segments in a batch get the same sip_id (starting from 1).
    - If the data starts with Eating, the first batch will have only Eating.
    - If the data ends with Not_Drinking, the last batch will have only Not_Drinking.
    - If the data ends with Eating, the last batch will have only Eating.
    - If there are more Not_Drinking or Eating segments, assign sip_id accordingly.
    """
    df_with_sip = df.copy()
    df_with_sip['sip_id'] = -1  # Initialize with -1

    for participant_id in sorted(df_with_sip['Participant_ID'].unique()):
        participant_mask = df_with_sip['Participant_ID'] == participant_id
        participant_data = df_with_sip[participant_mask]
        indices = participant_data.index.tolist()
        labels = participant_data['Label'].tolist()

        sip_id = 1
        i = 0
        n = len(indices)

        while i < n:
            # Not_Drinking segment
            not_drinking_indices = []
            while i < n and labels[i] == 'Not_Drinking':
                not_drinking_indices.append(indices[i])
                i += 1
            if not_drinking_indices:
                for idx in not_drinking_indices:
                    df_with_sip.at[idx, 'sip_id'] = sip_id

            # Eating segment
            eating_indices = []
            while i < n and labels[i] == 'Eating':
                eating_indices.append(indices[i])
                i += 1
            if eating_indices:
                for idx in eating_indices:
                    df_with_sip.at[idx, 'sip_id'] = sip_id

            # Only increment sip_id if we assigned at least one row in this batch
            if not_drinking_indices or eating_indices:
                sip_id += 1

    return df_with_sip

# Apply batch sip_id assignment
print("Assigning batch sip_id (Not_Drinking + Eating) to all participants...")
eating_data_with_sip = add_sip_id_batch(combined_csv_data)

# Check the results
print(f"Total rows: {len(eating_data_with_sip)}")
print(f"Rows with sip_id >= 1: {(eating_data_with_sip['sip_id'] >= 1).sum()}")
print(f"Rows with sip_id == -1: {(eating_data_with_sip['sip_id'] == -1).sum()}")
print(f"Unique sip_ids: {eating_data_with_sip['sip_id'].nunique()}")

# Show sip_id distribution
print("\nSip ID distribution:")
sip_dist = eating_data_with_sip['sip_id'].value_counts().sort_index()
print(sip_dist)

# Check by participant
print("\nSip ID distribution by participant:")
for participant_id in sorted(eating_data_with_sip['Participant_ID'].unique()):
    participant_data = eating_data_with_sip[eating_data_with_sip['Participant_ID'] == participant_id]
    unique_sips = participant_data['sip_id'].unique()
    print(f"  Participant {participant_id}: sip_ids {sorted(unique_sips)}")

# Show sample for participant 1 to verify the batch assignment
print("\nSample data for Participant 1 (last few rows):")
participant_1_data = eating_data_with_sip[eating_data_with_sip['Participant_ID'] == 1]
display(participant_1_data[['Participant_ID', 'Label', 'sip_id']].tail(20))

# Update the combined_csv_data
combined_csv_data = eating_data_with_sip

Assigning batch sip_id (Not_Drinking + Eating) to all participants...
Total rows: 25872
Rows with sip_id >= 1: 25872
Rows with sip_id == -1: 0
Unique sip_ids: 15

Sip ID distribution:
sip_id
1     2820
2     3404
3     3320
4     3784
5     3001
6     2460
7     1862
8     1724
9     1276
10     906
11     550
12     312
13     220
14     135
15      98
Name: count, dtype: int64

Sip ID distribution by participant:
  Participant 1: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11)]
  Participant 2: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
  Participant 3: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]
  Participant 4: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
  Participant 5: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]
  Participant 6: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
  Participant 7: sip_ids [np.int64(1)]
  Participant 8: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15)]
  Participant 9: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13)]
  Participant 10: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]
  Participant 11: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11)]
  Participant 12: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13)]
  Participant 13: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]
  Participant 14: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15)]
  Participant 15: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12)]
  Participant 16: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]
  Participant 17: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
  Participant 18: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7)]
  Participant 19: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7)]
  Participant 20: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
  Participant 21: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]
  Participant 22: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]
  Participant 23: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]
  Participant 24: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]
  Participant 25: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10)]
  Participant 26: sip_ids [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Sample data for Participant 1 (last few rows):

      Participant_ID         Label  sip_id
1180               1  Not_Drinking      11
1181               1  Not_Drinking      11
1182               1  Not_Drinking      11
1183               1  Not_Drinking      11
1184               1  Not_Drinking      11
1185               1  Not_Drinking      11
1186               1  Not_Drinking      11
1187               1  Not_Drinking      11
1188               1  Not_Drinking      11
1189               1  Not_Drinking      11
1190               1  Not_Drinking      11
1191               1  Not_Drinking      11
1192               1  Not_Drinking      11
1193               1  Not_Drinking      11
1194               1  Not_Drinking      11
1195               1  Not_Drinking      11
1196               1  Not_Drinking      11
1197               1  Not_Drinking      11
1198               1  Not_Drinking      11
1199               1  Not_Drinking      11

# Save the processed DataFrame to an Excel file

In [99]:
# Save the processed DataFrame to an Excel file
combined_csv_data.to_excel('eating_sequence_processed.xlsx', index=False)
print('Processed data saved.')

Processed data saved.

In [100]:
# Count total number of eating gestures (continuous 'Eating' sequences) in the whole dataset
# Each sequence of 'Eating' labels represents one complete eating gesture

labels = combined_csv_data['Label'].tolist()
participant_ids = combined_csv_data['Participant_ID'].tolist()

total_eating_gestures = 0
in_eating = False
current_gesture_start = None
eating_gestures = []
participant_gestures = {}
harsh_total_gestures = 0
alireza_total_gestures = 0

for i, (label, participant_id) in enumerate(zip(labels, participant_ids)):
    if label == 'Eating' and not in_eating:
        # Start of new eating gesture
        current_gesture_start = i
        in_eating = True
    elif label != 'Eating' and in_eating:
        # End of eating gesture
        eating_gestures.append((current_gesture_start, i-1))
        # Track which participant made this gesture
        if participant_id not in participant_gestures:
            participant_gestures[participant_id] = 0
        participant_gestures[participant_id] += 1
        
        # Add to respective totals based on participant ID
        if participant_id <= 6:  # Harsh's data
            harsh_total_gestures += 1
        else:  # Alireza's data
            alireza_total_gestures += 1
            
        in_eating = False
        current_gesture_start = None

# Handle case where last sequence extends to end of list
if in_eating:
    eating_gestures.append((current_gesture_start, len(labels)-1))
    participant_id = participant_ids[current_gesture_start]
    if participant_id not in participant_gestures:
        participant_gestures[participant_id] = 0
    participant_gestures[participant_id] += 1
    
    # Add final gesture to respective total
    if participant_id <= 6:
        harsh_total_gestures += 1
    else:
        alireza_total_gestures += 1

total_eating_gestures = len(eating_gestures)

print(f"Total number of complete eating gestures in the dataset: {total_eating_gestures}")
print(f"Each gesture is a continuous sequence of 'Eating' labels")
print("\nGestures by participant:")
for participant_id, gesture_count in sorted(participant_gestures.items()):
    print(f"Participant {participant_id}: {gesture_count} gestures")

print("\nTotal gestures by researcher:")
print(f"Harsh's data (Participants 1-6): {harsha_total_gestures} gestures")
print(f"Alireza's data (Remaining participants): {alireza_total_gestures} gestures")

Total number of complete eating gestures in the dataset: 190
Each gesture is a continuous sequence of 'Eating' labels

Gestures by participant:
Participant 1: 10 gestures
Participant 2: 4 gestures
Participant 3: 8 gestures
Participant 4: 4 gestures
Participant 5: 7 gestures
Participant 6: 4 gestures
Participant 8: 14 gestures
Participant 9: 12 gestures
Participant 10: 5 gestures
Participant 11: 10 gestures
Participant 12: 12 gestures
Participant 13: 7 gestures
Participant 14: 14 gestures
Participant 15: 11 gestures
Participant 16: 8 gestures
Participant 17: 4 gestures
Participant 18: 6 gestures
Participant 19: 6 gestures
Participant 20: 4 gestures
Participant 21: 5 gestures
Participant 22: 8 gestures
Participant 23: 7 gestures
Participant 24: 7 gestures
Participant 25: 9 gestures
Participant 26: 4 gestures

Total gestures by researcher:
Harsh's data (Participants 1-6): 37 gestures
Alireza's data (Remaining participants): 153 gestures